---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: helloworld-image-from-git
spec:
 inputs:
  resources:
    - name: git-source
      type: git
  params:
    - name: contextDir
      default: /workspace/git-source/registry/example
      description: The Docker build context Dir
    - name: mavenMirrorUrl
      default: "http://repo1.maven.org/maven2"
      description: The MAVEN_MIRROR_URL url to use
 outputs:
  resources:
    - name: builtImage
      type: image
 steps:
    - name: buildah-build-push
      image: quay.io/rhdevelopers/quarkus-java-builder
      imagePullPolicy: IfNotPresent
      env:
      - name: MAVEN_MIRROR_URL
        value: "${inputs.params.mavenMirrorUrl}"
      - name: WORK_DIR
        value: "${inputs.params.contextDir}/helloworld"
      - name: PUSH
        value: "true"
      - name: MVN_CMD_ARGS
        value: "clean -DskipTests install"
      - name: DESTINATION_NAME
        value: ${outputs.resources.builtImage.url}
      args:
       - "/usr/local/bin/maven-buildah.sh"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
        - mountPath: /root/.m2
          name: m2-cache
        - name: varlibcontainers
          mountPath: /var/lib/containers
    - name: update-image-url
      image: quay.io/rhdevelopers/tutorial-tools
      imagePullPolicy: IfNotPresent
      command: 
       - "yq"
      args:
        - "w"
        - "-i"
        - "deployment.yaml"  
        - "spec.template.spec.containers[0].image"
        - "${outputs.resources.builtImage.url}"
        - "-d*"
      workingDir: "${inputs.params.contextDir}"
    - name: run-kubectl
      image: quay.io/rhdevelopers/tutorial-tools
      imagePullPolicy: IfNotPresent
      command: 
       - "kubectl"
      args:
        - "apply"
        - "--filename"
        - "deployment.yaml"     
        - "--filename"
        - "service.yaml"   
      workingDir: "${inputs.params.contextDir}"
 volumes:
    - name: m2-cache
      persistentVolumeClaim:
        claimName: m2-cache
    - name: varlibcontainers
      emptyDir: {}
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: hello-world-maven
spec:
  serviceAccount: build-robot
  taskRef:
    name: helloworld-image-from-git
  inputs:
    resources:
    - name: git-source
      resourceRef:
        name: hello-git-source
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: helloworld-image