apiVersion: apps/v1
kind: Deployment
metadata:
  name: heloworld
spec:
  selector:
    matchLabels:
      app: heloworld
  template:
    metadata:
      labels:
        app: heloworld
    spec:
      containers:
      - name: heloworld
        image: "will be replaced by build"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: heloworld
spec:
  selector:
    app: heloworld
  ports:
  - port: 8080
    targetPort: 8080

